version: "3.9"
services:
  tomcat:
    image: tomcat
    container_name: campusparadigma_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - campusparadigma_db
      - email_server
    networks:
      - campusparadigma_net

  email_server_campusparadigma:
    image: djfarrelly/maildev
    container_name: email_server
    ports:
      - "25:25"
      - "80:80"
    restart: always
    networks:
      - campusparadigma_net

  campusparadigma_db:
    image: postgres
    container_name: campusparadigma_db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: pi
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: campusparadigma
    volumes:
      - $PWD/db_data:/var/lib/postgresql/data
    networks:
      - campusparadigma_net

networks:
  campusparadigma_net:
